# Python-Boilerplate/docker-compose.override.yml
services:
  app:
    build: .
    image: python-service-dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    environment:
      APP_ENV: dev
      APP_LOG_LEVEL: DEBUG
